# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.CharField(max_length=32)),
                ('src_href', models.CharField(max_length=256)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('abs_x', models.IntegerField()),
                ('abs_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('src_id', models.CharField(max_length=32)),
                ('src_href', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='puzzle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='puzzle.Puzzle'),
        ),
    ]
