# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='secret',
            field=models.CharField(default='old', max_length=128),
            preserve_default=False,
        ),
    ]
